Document: rss2ctdl
Title: Debian rss2ctdl Manual
Author: <insert document author here>
Abstract: This manual describes what rss2ctdl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rss2ctdl/rss2ctdl.sgml.gz

Format: postscript
Files: /usr/share/doc/rss2ctdl/rss2ctdl.ps.gz

Format: text
Files: /usr/share/doc/rss2ctdl/rss2ctdl.text.gz

Format: HTML
Index: /usr/share/doc/rss2ctdl/html/index.html
Files: /usr/share/doc/rss2ctdl/html/*.html

  
