# Makefile for Daphne on wxWindows/MSW built with Cygwin
# $Id$

TARGET          = daphne

MY_OBJECTS	= citclient.o enter.o express_message.o main.o message.o \
		prefs.o roomtree.o roomview.o selectuser.o send_express.o \
		servprops.o testwindow.o userlogin.o hosts.o \
		utils.o who.o

OBJECTS         = $(MY_OBJECTS)

WXDIR = /wx2
include $(WXDIR)/src/makeprog.g95
