// HE lang variables by Liron Newman, http://eesh.net

tinyMCE.addToLang('',{
bold_desc : 'מ&aring;דגש',
italic_desc : 'נט&aring;י',
underline_desc : 'ק&aring; תחתי',
striketrough_desc : 'ק&aring; ח&aring;&ouml;&auml;',
justifyleft_desc : 'ישר לשמאל',
justifycenter_desc : 'ישר למרכז',
justifyright_desc : 'ישר לימין',
justifyfull_desc : 'ישר לשני &auml;&ouml;דדים',
bullist_desc : 'רשימ&auml; חסרת סדר',
numlist_desc : 'רשימ&auml; מס&aring;דרת',
outdent_desc : '&auml;קטן כניס&auml;',
indent_desc : '&auml;גדל כניס&auml;',
undo_desc : 'בטל',
redo_desc : 'ב&ouml;ע ש&aring;ב',
link_desc : '&auml;כנס/ער&aring;ך קיש&aring;ר',
unlink_desc : 'בטל קיש&aring;ר',
image_desc : '&auml;כנס/ער&aring;ך תמ&aring;נ&auml;',
cleanup_desc : 'נק&auml; ק&aring;ד מב&aring;לגן',
focus_alert : 'יש לבח&aring;ר בשד&auml; עריכ&auml; לפני שניתן ל&auml;שתמש בפק&aring;ד&auml; ז&aring;.',
edit_confirm : '&auml;אם בר&ouml;&aring;נך ל&auml;שתמש במ&ouml;ב עריכ&auml; עשיר&auml; (WYSIWYG) עב&aring;ר שד&auml; טקסט ז&auml;?',
insert_link_title : '&auml;כנס/ער&aring;ך קיש&aring;ר',
insert : '&auml;כנס',
update : 'עדכן',
cancel : 'בטל',
insert_link_url : 'כת&aring;בת (URL) &auml;קיש&aring;ר',
insert_link_target : 'יעד',
insert_link_target_same : 'פתח את &auml;קיש&aring;ר בא&aring;ת&aring; חל&aring;ן',
insert_link_target_blank : 'פתח את &auml;קיש&aring;ר בחל&aring;ן חדש',
insert_image_title : '&auml;כנס/ער&aring;ך תמ&aring;נ&auml;',
insert_image_src : 'כת&aring;בת (URL) &auml;תמ&aring;נ&auml;',
insert_image_alt : 'תיא&aring;ר &auml;תמ&aring;נ&auml;',
help_desc : 'עזר&auml;',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'פע&aring;ל&aring;ת &auml;עתק&auml;/גזיר&auml;/&auml;דבק&auml; אינן נתמכ&aring;ת תחת Mozilla &aring;-Firefox.\n&auml;אם בר&ouml;&aring;נך לקבל מידע נ&aring;סף א&aring;ד&aring;ת נ&aring;שא ז&auml;?',
popup_blocked : 'סליח&auml;, אך שמנ&aring; לב כי ח&aring;סם &auml;חל&aring;נ&aring;ת &auml;ק&aring;פ&ouml;ים שלך חסם חל&aring;ן שמ&auml;&aring;&aring;&auml; חלק מ&auml;ייש&aring;ם. ת&ouml;טרך לבטל את חסימת &auml;חל&aring;נ&aring;ת &auml;ק&aring;פ&ouml;ים באתר ז&auml; כדי לנ&ouml;ל כלי ז&auml; במל&aring;א&aring;.'
});
