#!/bin/sh
#
# run me after checking Citadel out of CVS.
#
aclocal
libtoolize --force
autoconf
autoheader

echo
echo This script has been tested with autoconf 2.52, libtool 1.4.2, and
echo automake 1.5. Other versions may work, but I recommend the latest
echo compatible versions of these.
echo
echo Some versions of libtool may have outputted, above, a spurious warning
echo that you have to regenerate your aclocal.m4. This is a mostly harmless bug
echo and can be ignored.
echo
echo Also note that autoconf, automake, and libtool should all be configured
echo with the same prefix.
echo
