#!/bin/bash
# find out the package version from conf
./bootstrap

export `grep PACKAGE_VERSION= configure |sed -e "s;';;g" -e "s;PACKAGE;CITADEL;"`

PACKAGE_VERSION=`cat packageversion`
DATE=`date '+%a, %d %b %Y %H:%I:00 %z'`
ACTUAL_DIR=`pwd`

if echo "$ACTUAL_DIR" |grep -q "$CITADEL_VERSION"; then
	echo "directory ($ACTUAL_DIR) naming scheme seems right. nothing done."
else
	done=false
	if test -L "$ACTUAL_DIR"; then 
		SYMLINK_=`pwd`
		SYMLINK=`ls -l $SYMLINK_|sed "s;.*-> ;;"`
		if ls -l $SYMLINK_|grep -q "$CITADEL_VERSION"; then
			done=true
		fi
	else
		SYMLINK=`pwd|sed "s;.*/;;"`
	fi
	if test "$done" = "false"; then 
		cd ..
		mv -- $SYMLINK "citadel-$CITADEL_VERSION"
		ln -sf "citadel-$CITADEL_VERSION" citadel
		cd "citadel-$CITADEL_VERSION"
	else
		cd "../citadel-$CITADEL_VERSION"
	fi
	
fi


case $1 in
	debian)

#dpkg-source: warning: source directory `./citadel' is not <sourcepackage>-<upstreamversion> `citadel-6.61'

		if grep -q "($CITADEL_VERSION" debian/changelog; then
			echo rebuilding package.
		else
			echo "citadel (${CITADEL_VERSION}-${PACKAGE_VERSION}) unstable; urgency=low

  * update to actual Citadel SVN. many new features. see Packages changelog.

 -- Wilfried Goesgens <citadel@outgesourced.org>  $DATE

" >/tmp/citadel_changelog
			cat debian/changelog >>/tmp/citadel_changelog
			mv /tmp/citadel_changelog debian/changelog

		fi
		if test "$2" == "src"; then
		    cd ..; dpkg-source -b "citadel-$CITADEL_VERSION"
		else
		    fakeroot dpkg-buildpackage
		fi
	;;
	*)
		echo "Not yet implemented. we have: debian "
		;;
esac
