#!/bin/bash
# find out the package version from conf
if test -x Makefile; then
    make clean
fi

./bootstrap

export `grep PACKAGE_VERSION= configure |sed -e "s;';;g" -e "s;PACKAGE;CITADEL;"`

PACKAGE_VERSION=`cat packageversion`
DATE=`date '+%a, %d %b %Y %H:%I:00 %z'`
ACTUAL_DIR=`pwd`

if echo "$ACTUAL_DIR" |grep -q "$CITADEL_VERSION"; then
	echo "directory ($ACTUAL_DIR) naming scheme seems right. nothing done."
else
	done=false
	if test -L "$ACTUAL_DIR"; then 
		SYMLINK_=`pwd`
		SYMLINK=`ls -l $SYMLINK_|sed "s;.*-> ;;"`
		if ls -l $SYMLINK_|grep -q "$CITADEL_VERSION"; then
			done=true
		fi
	else
		SYMLINK=`pwd|sed "s;.*/;;"`
	fi
	if test "$done" = "false"; then 
		cd ..
		mv -- $SYMLINK "citadel-$CITADEL_VERSION"
		ln -sf "citadel-$CITADEL_VERSION" citadel
		cd "citadel-$CITADEL_VERSION"
	else
		cd "../citadel-$CITADEL_VERSION"
	fi
	
fi


case $1 in
    debian)
	if grep -q "($CITADEL_VERSION" debian/changelog; then
	    echo rebuilding package.
	else
	    echo "citadel (${CITADEL_VERSION}-${PACKAGE_VERSION}) unstable; urgency=low

  * update to actual Citadel SVN. many new features. see Packages changelog.

 -- Wilfried Goesgens <citadel@outgesourced.org>  $DATE

" >/tmp/citadel_changelog
	    cat debian/changelog >>/tmp/citadel_changelog
	    mv /tmp/citadel_changelog debian/changelog
	    
	fi
	if test "$2" == "src"; then
	    cd ..; dpkg-source -b "citadel-$CITADEL_VERSION"
	else
	    fakeroot dpkg-buildpackage
	fi
	;;
    csw)
	if !test -d ~/pkgs/; then
	    mkdir ~/pkgs
	fi
	echo "
PKG=CSWcitadel
NAME=citadel - The groupware server for Web 2.0
VERSION=${PACKAGE_VERSION}
CATEGORY=application
VENDOR=http://www.citadel.org/  packaged for CSW by Wilfried Goesgens
HOTLINE=https://uncensored.citadel.org/ Room citadel support
EMAIL=citadel@outgesourced.org
" >~/pkgs/citadel
	export LDFLAGS='-L/opt/csw/lib -L /usr/local/lib'
	export CFLAGS='-I/opt/csw/include -I/usr/local/include  -DDISABLE_CURSES'
	./configure \
	    --with-db=/opt/csw/bdb44 \
	    --with-ical=/usr/local/ \
	    --without-curses \
	    --with-prefix=/opt/csw/ \
	    --with-datadir=/opt/csw/var/lib/citadel \
	    --with-sysconfdir=/opt/csw/etc/citadel \
	    --with-ssldir=/opt/csw/etc/ssl/citadel/ \
	    --with-spooldir=/opt/csw/var/spool/citadel \
	    --with-rundir=/opt/csw/var/run/citadel \
	    --with-docdir=/opt/csw/share/doc/citadel-doc/ \
	    --with-pam \
	    --with-zlib \
	    --with-ldap \
	    --with-libsieve
	    
	gmake citserver aidepost msgform citmail userlist sendcommand base64 whobbs citadel
	gmake DESTDIR=$ACTUAL_DIR/cswstage install-new
	


	;;
    sourcedist)
	cd ..; tar --exclude .svn -cvzf citadel-$CITADEL_VERSION.tgz citadel-$CITADEL_VERSION/
	;;
	*)
		echo "Not yet implemented. we have: debian "
		;;
esac
