extern char fullname[32];
extern unsigned room_flags;
extern char room_name[32];
extern struct CtdlServInfo serv_info;
extern char axlevel;
extern char is_room_aide;
extern unsigned userflags;
extern char sigcaught;
extern char editor_path[256];
extern char printcmd[256];
extern char have_xterm;
extern char rc_username[32];
extern char rc_password[32];
extern char rc_floor_mode;
extern char express_msgs;
void logoff(int code);
void formout(char *name);
void sighandler(int which_sig);
