/* $Id$ */
void master_startup (void);
void master_cleanup (void);
void cleanup_stuff (void *arg);
void set_wtmpsupp (char *newtext);
void cmd_info (void);
void cmd_rchg (char *newroomname);
void cmd_hchg (char *newhostname);
void cmd_uchg (char *newusername);
void cmd_time (void);
int is_public_client (char *where);
void cmd_iden (char *argbuf);
void cmd_stel (char *cmdbuf);
void cmd_mesg (char *mname);
void cmd_emsg (char *mname);
void cmd_rwho (void);
void cmd_term (char *cmdbuf);
void cmd_more (void);
void cmd_echo (char *etext);
void cmd_ipgm (char *argbuf);
void cmd_down (void);
void cmd_scdn (char *argbuf);
void cmd_extn (char *argbuf);
void *context_loop (struct CitContext *con);
