#!/bin/sh
#
# Script to generate $C_FILE
#



CUR_DIR=`pwd`
C_FILE="$CUR_DIR/modules_init.c"
H_FILE="$CUR_DIR/modules_init.h"

echo -e "Scanning extension modules for entry points."


#start ofs the files which inturn removes any existing file
#
echo -e "/*" > $C_FILE
echo -e " * $C_FILE" >> $C_FILE
echo -e " * Auto generated by mk_modules_init.sh DO NOT EDIT THIS FILE" >> $C_FILE
echo -e " */\n\n\n" >> $C_FILE

#echo -e "#include \"sysdep.h\"\n" >> $C_FILE
echo -e "#include <stdlib.h>\n" >> $C_FILE
#echo -e "#include <ctype.h>\n" >> $C_FILE
#echo -e "#include \"citadel.h\"\n" >> $C_FILE
echo -e "#include \"modules_init.h\"\n" >> $C_FILE
echo -e "#include \"sysdep_decls.h\"\n" >> $C_FILE
echo -e "\n\n\n" >> $C_FILE
echo -e "void LogPrintMessages(long err);" >> $C_FILE
echo -e "static long DetailErrorFlags;" >> $C_FILE
echo -e "\n\n\n" >> $C_FILE

echo -e "void initialise_modules (void)" >> $C_FILE
echo -e "{" >> $C_FILE
echo -e "\tlong filter;\n\n" >> $C_FILE
echo -e -n "\t" >> $C_FILE
echo -E "lprintf(CTDL_INFO, \"New citadel module init proceedure.\n\");" >> $C_FILE

#start the header file
echo -e "/*" > $H_FILE
echo -e " * $H_FILE" >> $H_FILE
echo -e " * Auto generated by mk_modules_init.sh DO NOT EDIT THIS FILE" >> $H_FILE
echo -e " */\n\n\n" >> $H_FILE
echo -e "#ifndef MODULES_INIT_H" >> $H_FILE
echo -e "#define MODULES_INIT_H\n" >> $H_FILE
echo -e "#include \"ctdl_module.h\"\n" >> $H_FILE
echo -e "void initialise_modules (void) ;\n" >> $H_FILE


for i in serv_*.c
do
	RES=X`grep CTDL_MODULE_INIT $i | cut -f2 -d\( | cut -f1 -d\)`
	if [ $RES != "X" ] ; then
		RES_OUT=`echo $RES | cut -b2-`
		echo -e "Found entry point in file $i"
		echo -e -n "\t" >> $C_FILE
		echo -E "lprintf (CTDL_INFO, \"%s\n\", CTDL_INIT_CALL($RES_OUT));" >> $C_FILE
		echo -E "CTDL_MODULE_INIT($RES_OUT) ;" >> $H_FILE
	fi
done


if [ -d "modules" ] ; then
	cd modules
	for j in *
	do
		if [ -d $j ] ; then
			cd $j
			for k in *.c
			do
				if [ -f "$k" ] ; then
					RES=X`grep CTDL_MODULE_INIT $k | cut -f2 -d\( | cut -f1 -d\)`
					if [ $RES != "X" ] ; then
						RES_OUT=`echo $RES | cut -b2-`
						echo -e "Found entry point in file modules/$j/$k"
						echo -n "\t" >> $C_FILE
						echo -E "lprintf (CTDL_INFO, "%s\n", CTDL_INIT_CALL($RES_OUT));" >> $C_FILE
						echo -E "CTDL_MODULE_INIT($RES_OUT) ;" >> $H_FILE
					fi
				fi
			done
		fi
	done
fi

cd $CUR_DIR

if [ -d "user_modules" ] ; then
	cd user_modules
	for j in *
	do
		if [ -d $j ] ; then
			cd $j
			for k in *.c
			do
				if [ -f "$k" ] ; then
					RES=X`grep CTDL_MODULE_INIT $k | cut -f2 -d\( | cut -f1 -d\)`
					if [ $RES != "X" ] ; then
						RES_OUT=`echo $RES | cut -b2-`
						echo -e "Found entry point in file user_modules/$j/$k"
						echo -n "\t" >> $C_FILE
						echo -E "lprintf (CTDL_INFO, "%s\n", CTDL_INIT_CALL($RES_OUT));" >> $C_FILE
						echo -E "CTDL_MODULE_INIT($RES_OUT) ;" >> $H_FILE
					fi
				fi
			done
		fi
	done
fi

cd $CUR_DIR

echo -e "\n\n" >> $C_FILE
echo -e "\tfor (filter = 1; filter != 0; filter = filter << 1)" >> $C_FILE
echo -e "\t\tif ((filter & DetailErrorFlags) != 0)" >> $C_FILE
echo -e "\t\t\tLogPrintMessages(filter);" >> $C_FILE
echo -e "}" >> $C_FILE


echo -e "\n#endif /* MODULES_INIT_H */" >> $H_FILE
