void lprintf (int loglevel, const char *format, ...);
void init_sysdep (void);
void begin_critical_section (int which_one);
void end_critical_section (int which_one);
int ig_tcp_server (int port_number, int queue_len);
struct CitContext *MyContext (void);
struct CitContext *CreateNewContext (void);
void InitMyContext (struct CitContext *con);
void RemoveContext (struct CitContext *con);
int session_count (void);
void client_write (char *buf, int nbytes);
void cprintf (const char *format, ...);
int client_read_to (char *buf, int bytes, int timeout);
int client_read (char *buf, int bytes);
int client_gets (char *buf);
void sysdep_master_cleanup (void);
void cleanup (int exit_code);
void kill_session (int session_to_kill);
void *sd_context_loop (struct CitContext *con);
void start_daemon (int do_close_stdio);
void cmd_nset (char *cmdbuf);
int convert_login (char *NameToConvert);
