#!/bin/sh

# Citadel/UX Utilities Menu (shell script)
# version 1.1 - July 1999
# see copyright.txt for copyright information

if test -n "$PAGER"
then
	MORECMD=$PAGER
elif test -n "$LESSOPEN"
then
	MORECMD=less
else
	MORECMD=more
fi

while true
do
	clear
	echo
	echo
	echo "                    Citadel/UX Utilities Menu"
	cat <<!!

 a. Citadel/UX login                     g. 
 b.                                      h. Read call log
 c. Calling statistics                   i. 
 d.                                      j. Who is logged in
 e.                                      k. Setup and configuration
 f. User list                            q. Quit

!!
	echo "Please enter your selection:"
	read x
	case $x in
		[a,A])	./citadel
			;;
		[c,C])	./stats |$MORECMD
			;;
		[f,F])	clear
			./userlist |$MORECMD
			;;
		[h,H])	./readlog |$MORECMD
			;;
		[j,J])	./whobbs |$MORECMD
			;;
		[k,K])  clear
			./setup
			;;
		[q,Q])	clear
			break;;
		!)	sh
			;;
		*)	echo "Selection $x is not available"
			sleep 1
			;;
		esac
	done
