#!/bin/bash
if test -x Makefile; then
    make clean
fi
./bootstrap
export `grep PACKAGE_VERSION= configure |sed -e "s;';;g" -e "s;PACKAGE;WEBCIT;"`

PACKAGE_VERSION=`cat packageversion`
DATE=`date '+%a, %d %b %Y %H:%I:00 %z'`
ACTUAL_DIR=`pwd`


rm -rf debian/citadel-webcit debian/tmp/
if echo "$ACTUAL_DIR" |grep -q "$WEBCIT_VERSION"; then
	echo "directory ($ACTUAL_DIR) naming scheme seems right. nothing done."
else
	done=false
	if test -L "$ACTUAL_DIR"; then 
		SYMLINK_=`pwd`
		SYMLINK=`ls -l $SYMLINK_|sed "s;.*-> ;;"`
		if ls -l $SYMLINK_|grep -q "$WEBCIT_VERSION"; then
			done=true
		fi
	else
		SYMLINK=`pwd|sed "s;.*/;;"`
	fi
	if test "$done" = "false"; then 
		cd ..
		ln -sf webcit "webcit-$WEBCIT_VERSION"
		cd "webcit-$WEBCIT_VERSION"
	else
		cd "../webcit-$WEBCIT_VERSION"
	fi
	
fi

case $1 in
    debian)
	if grep -q "($WEBCIT_VERSION" debian/changelog; then
	    echo rebuilding package.
	else
	    echo "Upstream Version higher than local."	    
	fi
	if test "$2" == "src"; then
	    cd ..
	    rm -rf tmp
	    mkdir tmp
	    cp -rL webcit-$WEBCIT_VERSION tmp
	    cd tmp/webcit-$WEBCIT_VERSION
	    rm -rf `find -name .svn ` svn*tmp* build-stamp configure-stamp *~ config.guess  config.log config.status autom4te.cache Makefile 
	    find -type f -exec chmod a-x {} \;
	    chmod a+x configure debian/rules po/create-pot.sh mk_module_init.sh
	    cd ..
	    tar -chzf webcit_${WEBCIT_VERSION}.orig.tar.gz webcit-${WEBCIT_VERSION}/ --exclude "debian/*"
	    pwd
	    cd  webcit-${WEBCIT_VERSION}; debuild -S -sa -kw.goesgens@outgesourced.org
	else
	    fakeroot dpkg-buildpackage
	fi
	;;
    sourcedist)
	if test "$2" == "dfsg"; then
	    NONDFSG=-"-exclude static/webcit_icons/openid-small.gif"
	fi
	cd ..; tar \
	    --exclude ".gitignore" \
	    --exclude "*.lo" \
	    --exclude "*.o" \
	    --exclude "*.d" \
	    --exclude "autom4te.cache/*" \
	    --exclude "debian/*" \
	    --exclude "sysdep.h" \
	    \
	    $NONDFSG \
	    \
	    -cvhzf webcit-${WEBCIT_VERSION}.tar.gz webcit-${WEBCIT_VERSION}/
	;;
    i18n)
	./webcit -G `pwd`/i18n_templatelist.c
	cd po;  ./create-pot.sh
	;;
    *)
	echo "Not yet implemented. we have: debian, sourcedist, i18n (needs ready compiled & installed webcit in your system)"
	;;
esac
