#!/bin/bash
if test -x Makefile; then
    make clean
fi
./bootstrap
export `grep PACKAGE_VERSION= configure |sed -e "s;';;g" -e "s;PACKAGE;WEBCIT;"`

PACKAGE_VERSION=`cat packageversion`
DATE=`date '+%a, %d %b %Y %H:%I:00 %z'`
ACTUAL_DIR=`pwd`

if echo "$ACTUAL_DIR" |grep -q "$WEBCIT_VERSION"; then
	echo "directory ($ACTUAL_DIR) naming scheme seems right. nothing done."
else
	done=false
	if test -L "$ACTUAL_DIR"; then 
		SYMLINK_=`pwd`
		SYMLINK=`ls -l $SYMLINK_|sed "s;.*-> ;;"`
		if ls -l $SYMLINK_|grep -q "$WEBCIT_VERSION"; then
			done=true
		fi
	else
		SYMLINK=`pwd|sed "s;.*/;;"`
	fi
	if test "$done" = "false"; then 
		cd ..
		mv -- $SYMLINK "webcit-$WEBCIT_VERSION"
		ln -sf "webcit-$WEBCIT_VERSION" webcit
		cd "webcit-$WEBCIT_VERSION"
	else
		cd "../webcit-$WEBCIT_VERSION"
	fi
	
fi

case $1 in
    debian)
	if grep -q "($WEBCIT_VERSION" debian/changelog; then
	    echo rebuilding package.
	else
	    echo "Upstream Version higher than local."	    
	fi
	if test "$2" == "src"; then
	    cd ..
	    rm -rf tmp
	    mkdir tmp
	    cp -a webcit-$WEBCIT_VERSION tmp
	    cd tmp/webcit-$WEBCIT_VERSION
	    rm -rf `find -name .svn ` svn*tmp* build-stamp configure-stamp *~ config.guess  config.log config.status autom4te.cache
	    cd ..
	    tar -czf webcit_${WEBCIT_VERSION}.orig.tar.gz webcit-${WEBCIT_VERSION}/ --exclude "debian/*"
	    pwd
	    cd  webcit-${WEBCIT_VERSION}; debuild -S -sa -kw.goesgens@outgesourced.org
	else
	    fakeroot dpkg-buildpackage
	fi
	;;
    sourcedist)
	cd ..; tar --exclude .svn --exclude "debian/*" -cvzf webcit-${WEBCIT_VERSION}.tar.gz webcit-${WEBCIT_VERSION}/
	;;
    *)
	echo "Not yet implemented. we have: debian "
	;;
esac
