/*
 * child.h: prototypes for the `webcit' child process
 *
 * $Id$
 */

void become_logged_in(char *, char *, char *);
void do_login(void);
void display_login(char *mesg);
void do_welcome(void);
void do_logout(void);
void display_main_menu(void);
void display_advanced_menu(void);
void list_all_rooms_by_floor(void);
void slrp_highest(void);
void gotonext(void);
void ungoto(void);
void get_serv_info(void);
int connectsock(char *host, char *service, char *protocol);
void serv_gets(char *strbuf);
void serv_puts(char *string);
void whobbs(void);
void fmout(FILE *fp);
void wDumpContent(void);
void serv_printf(const char *format, ...);
char *bstr(char *key);
char *urlesc(char *);
void urlescputs(char *);
void output_headers(int);
void wprintf(const char *format, ...);
void extract(char *dest, char *source, int parmnum);
int extract_int(char *source, int parmnum);
void output_static(char *what);
void escputs(char *strbuf);
void url(char *buf);
void escputs1(char *strbuf, int nbsp);
long extract_long(char *source, long int parmnum);
void dump_vars(void);
void embed_main_menu(void);
void serv_read(char *buf, int bytes);
int haschar(char *st, char ch);
void readloop(char *oper);
void text_to_server(char *ptr);
void display_enter(void);
void post_message(void);
void confirm_delete_msg(void);
void delete_msg(void);
void confirm_move_msg(void);
void move_msg(void);
void userlist(void);
void showuser(void);
void display_page(void);
void page_user(void);
void do_chat(void);
void display_private(char *rname, int req_pass);
void goto_private(void);
void zapped_list(void);
void display_zap(void);
void zap(void);
void display_error(char *);
void display_success(char *);
void display_entroom(void);
void entroom(void);
void display_editroom(void);
void editroom(void);
void server_to_text(void);
void save_edit(char *description, char *enter_cmd, int regoto);
void display_edit(char *description, char *check_cmd,
                char *read_cmd, char *save_cmd);
void gotoroom(char *gname, int display_name);
void confirm_delete_room(void);
void delete_room(void);
void validate(void);
void mime_parser(char *, int, char *);
void handle_multipart(char *, int, char *);
void display_graphics_upload(char *, char *, char *);
void do_graphics_upload(char *upl_cmd);
void serv_read(char *buf, int bytes);
void serv_gets(char *strbuf);
void serv_write(char *buf, int nbytes);
void serv_puts(char *string);
void serv_printf(const char *format, ...);
void load_floorlist(void);
void select_floor_to_edit_pic(void);
void display_reg(int);
void register_user(void);
void display_changepw(void);
void changepw(void);
