#!/bin/bash
# find out the package version from conf
if test -f Makefile; then
    make distclean
fi

./bootstrap

export `grep PACKAGE_VERSION= configure |sed -e "s;';;g" -e "s;PACKAGE;LIBCITADEL;"  -e "s;4.;;"`

DATE=`date '+%a, %d %b %Y %H:%I:00 %z'`
ACTUAL_DIR=`pwd`


rm -rf debian/libcitadel debian/libcitadel-dev debian/libcitadel1 debian/libcitadel1-dbg debian/tmp
if echo "$ACTUAL_DIR" |grep -q "$LIBCITADEL_VERSION"; then
	echo "directory ($ACTUAL_DIR) naming scheme seems right. nothing done."
else
	done=false
	if test -L "$ACTUAL_DIR"; then 
		SYMLINK_=`pwd`
		SYMLINK=`ls -l $SYMLINK_|sed "s;.*-> ;;"`
		if ls -l $SYMLINK|grep -q "$LIBCITADEL_VERSION"; then
			done=true
		fi
	else
		SYMLINK=`pwd|sed "s;.*/;;"`
	fi
	if test "$done" = "false"; then 
		cd ..
		ln -sf libcitadel "libcitadel-$LIBCITADEL_VERSION" 
		cd "libcitadel-$LIBCITADEL_VERSION"
	else
		cd "../libcitadel-$LIBCITADEL_VERSION"
	fi
	
fi


case $1 in
    debian)
	if grep -q "($LIBCITADEL_VERSION" debian/changelog; then
	    echo rebuilding package.
	else
	    echo "Upstream Version higher than local."
	    
	fi
	if test "$2" == "src"; then
	    cd ..
	    rm -rf tmp
	    mkdir tmp
	    cp -rL libcitadel-$LIBCITADEL_VERSION tmp
	    cd tmp/libcitadel-$LIBCITADEL_VERSION
	    rm -rf `find -name .svn ` svn*tmp config.log config.status `find -name .libs`
	    find -type f -exec chmod a-x {} \;
	    chmod a+x configure
	    cd ..
	    tar -chzf libcitadel_${LIBCITADEL_VERSION}.orig.tar.gz libcitadel-${LIBCITADEL_VERSION}/ --exclude "debian/*"
	    pwd
	    cd  libcitadel-${LIBCITADEL_VERSION}; debuild -S -sa -kw.goesgens@outgesourced.org
	else
	    fakeroot dpkg-buildpackage
	fi
	;;
    csw)
	if !test -d ~/pkgs/; then
	    mkdir ~/pkgs
	fi
	echo "
PKG=CSWlibcitadel
NAME=libcitadel - The groupware server for Web 2.0
VERSION=${PACKAGE_VERSION}
CATEGORY=application
VENDOR=http://www.citadel.org/  packaged for CSW by Wilfried Goesgens
HOTLINE=https://uncensored.citadel.org/ Room citadel support
EMAIL=citadel@outgesourced.org
" >~/pkgs/citadel
	export LDFLAGS='-L/opt/csw/lib -L /usr/local/lib'
	export CFLAGS='-I/opt/csw/include -I/usr/local/include  -DDISABLE_CURSES'
	./configure \
	    --with-db=/opt/csw/bdb44 \
	    --with-ical=/usr/local/ \
	    --without-curses \
	    --with-prefix=/opt/csw/ \
	    --with-datadir=/opt/csw/var/lib/citadel \
	    --with-sysconfdir=/opt/csw/etc/citadel \
	    --with-ssldir=/opt/csw/etc/ssl/citadel/ \
	    --with-spooldir=/opt/csw/var/spool/citadel \
	    --with-rundir=/opt/csw/var/run/citadel \
	    --with-docdir=/opt/csw/share/doc/citadel-doc/ \
	    --with-pam \
	    --with-zlib \
	    --with-ldap \
	    --with-libsieve
	    
	gmake citserver aidepost msgform citmail userlist sendcommand base64 whobbs citadel
	gmake DESTDIR=$ACTUAL_DIR/cswstage install-new
	


	;;
    sourcedist)
	cd ..; tar \
	    --exclude ".gitignore" \
	    --exclude "*.lo" \
	    --exclude "*.o" \
	    --exclude "*.d" \
	    --exclude "autom4te.cache/*" \
	    --exclude "debian/*" \
	    --exclude "sysdep.h" \
	    \
	    --exclude .libs \
	    --exclude tests/testdata \
	    \
	    -chvzf libcitadel-$LIBCITADEL_VERSION.tar.gz libcitadel-$LIBCITADEL_VERSION/
	;;
	version)
		echo This would build libcitadel-$LIBCITADEL_VERSION
		;;
	*)
		echo "Not yet implemented. we have: debian, sourcedist "
		;;
esac
