all:
	@echo "- Preparing build system from CVS sources..."
	@echo -n "  "
	@aclocal
	@echo -n "."
	@autoheader
	@echo -n "."
	@automake
	@echo -n "."
	@autoconf
	@echo -n "."
	@echo "Done!"

clean:
	@echo "- Preparing for CVS operation..."
	@find . -name Makefile -or -name Makefile.in | xargs rm -f
	@rm -f configure aclocal.m4 configure config.status config.cache config.log config.h
	@echo "  Done!"
