#!/usr/bin/perl

while( $file = <*.java> ) {
	$file =~ s/[\r\n]//g;

	$dirty = 0;

	$output = $file;
	$output =~ s/java$/class/;

	if( -f $output ) {
		@out = stat( $output );
		@in = stat( $file );
		if( $in[9] > $out[9] ) { $dirty = 1; }
		}
	else { $dirty = 1; }

	if( $dirty ) {
		$objs .= " $file";
		}
	}

if( $objs ) {
	print "javac $objs\n";
	system( "javac $objs" );
	}
else {
	print "Nothing to make\n";
	}
