all: MultiUserChat102.class wcCitUtil.class wcCitServer.class wcchat.class

MultiUserChat102.class: MultiUserChat102.java
	javac MultiUserChat102.java

wcCitServer.class: wcCitServer.java
	javac wcCitServer.java

wcCitUtil.class: wcCitUtil.java
	javac wcCitUtil.java

wcchat.class: wcchat.java
	javac wcchat.java
