#! /bin/sh
. /usr/share/debconf/confmodule
set -e

. /usr/share/debconf/confmodule
db_version 2.0

case "$1" in
  remove)
    ;;
  purge)
	rmdir "/etc/citadel/help"
	rmdir "/etc/citadel/messages"

	echo "/var/lib/citadel/data not removed, as it may contain your personal data."
	db_purge
	db_go
	;;
  disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 1;;
esac

exit 0
