debian/tmp/usr/sbin/citserver
debian/tmp/usr/sbin/aidepost
debian/tmp/usr/sbin/msgform
debian/tmp/usr/sbin/citmail
debian/tmp/usr/sbin/userlist
debian/tmp/usr/sbin/sendcommand
debian/tmp/usr/sbin/base64
debian/tmp/usr/lib/citadel-server/setup
debian/tmp/usr/sbin/chkpwd
debian/tmp/etc/citadel/mail.aliases
debian/tmp/etc/citadel/public_clients
debian/tmp/etc/citadel/messages/
debian/tmp/etc/citadel/help/
debian/tmp/usr/share/doc/citadel-doc/database_cleanup.sh

